[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11>=2.11",
]
build-backend = "scikit_build_core.build"


[project]
name = "agnsf"
version = "0.1.0"
description = "Astronomical structure function analysis"
requires-python = ">=3.10"


[tool.scikit-build]
build-dir = "build/{wheel_tag}"
wheel.packages = ["python/agnsf"]